name: Auto create issue

on:
  workflow_dispatch:
    inputs:
      card_content:
        description: 'Card content (used for manual trigger)'
        required: false
  project_card:
    types:
      - created

jobs:
  auto_create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue for new project card
        id: create_issue
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            CARD_CONTENT=${{ github.event.inputs.card_content }}
          else
            CARD_CONTENT=${{ github.event.project_card.note }}
          fi

          ISSUE_TITLE=$(echo "$CARD_CONTENT" | head -n1)
          ISSUE_BODY=$(echo -e "$CARD_CONTENT" | tail -n +2)

          ISSUE_PAYLOAD=$(echo '{}' | jq --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" '. | .title=$title | .body=$body')
          ISSUE_RESPONSE=$(gh issue create --json title,body --title "$ISSUE_TITLE" --body "$ISSUE_BODY")
          ISSUE_URL=$(echo "$ISSUE_RESPONSE" | jq -r '.html_url')

          echo "::set-output name=issue_url::$ISSUE_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Display created issue URL
        run: |
          echo "Created issue: ${{ steps.create_issue.outputs.issue_url }}"
